name: data_engg
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aom=3.12.1=h00a0c3c_0
  - asttokens=3.0.0=py314haa95532_0
  - attrs=25.4.0=py314haa95532_2
  - blas=1.0=mkl
  - bottleneck=1.4.2=py314h2b7f5b3_1
  - brotlicffi=1.2.0.0=py314h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2026.01.04=py314haa95532_0
  - cffi=2.0.0=py314h02ab6af_1
  - charset-normalizer=3.4.4=py314haa95532_0
  - colorama=0.4.6=py314haa95532_0
  - comm=0.2.3=py314haa95532_0
  - contourpy=1.3.3=py314h214f63a_0
  - cycler=0.12.1=py314haa95532_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.16=py314h885b0b7_1
  - decorator=5.2.1=py314haa95532_0
  - executing=2.2.1=py314haa95532_0
  - expat=2.7.4=hd7fb8db_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.61.0=py314h02ab6af_0
  - freeglut=3.8.0=hfcef157_0
  - freetype=2.14.1=hfbffc0b_0
  - fribidi=1.0.16=haf45083_0
  - graphite2=1.3.14=hd77b12b_1
  - h11=0.16.0=py314haa95532_1
  - harfbuzz=12.3.0=h3ef6528_1
  - icu=73.1=h6c2663c_0
  - idna=3.11=py314haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=6.31.0=py314h56ec5ee_0
  - ipython=9.7.0=py314haa95532_0
  - ipython_pygments_lexers=1.1.1=py314haa95532_0
  - jedi=0.19.2=py314haa95532_0
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.8.0=py314haa95532_0
  - jupyter_core=5.9.1=py314haa95532_0
  - kiwisolver=1.4.9=py314h03f52e7_0
  - lcms2=2.17=h3732fa5_0
  - lerc=4.0.0=h5da7b33_0
  - libavif=1.3.0=h5bd13ec_0
  - libclang13=21.1.8=default_h643f374_0
  - libdeflate=1.22=h5bf469e_0
  - libexpat=2.7.4=hd7fb8db_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.86.3=h9bccc14_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libllvm21=21.1.8=h3aa9ab2_0
  - libmpdec=4.0.0=h827c3e9_0
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.54=ha15c746_0
  - libpq=17.6=h652a1e2_0
  - libsodium=1.0.20=h83e8143_0
  - libtiff=4.7.1=h3a18249_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib=3.10.8=py314haa95532_0
  - matplotlib-base=3.10.8=py314h7ae407a_0
  - matplotlib-inline=0.2.1=py314haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py314h0b37514_0
  - mkl_fft=2.1.1=py314h281c9fe_0
  - mkl_random=1.3.0=py314hdbada53_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - numexpr=2.14.1=py314h2592778_0
  - openssl=3.0.19=hbb43b14_0
  - outcome=1.3.0=py314haa95532_0
  - packaging=25.0=py314haa95532_1
  - parso=0.8.5=py314haa95532_0
  - pcre2=10.46=h5740b90_0
  - pillow=12.1.0=py314h6b7a805_0
  - pip=25.3=pyh0d26453_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.0=py314haa95532_0
  - prompt-toolkit=3.0.52=py314haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py314h02ab6af_1
  - pure_eval=0.2.3=py314haa95532_0
  - pycparser=2.23=py314haa95532_0
  - pygments=2.19.2=py314haa95532_0
  - pyparsing=3.2.5=py314haa95532_0
  - pyqt=5.15.11=py314h816affc_0
  - pyqt5-sip=12.17.0=py314h02ab6af_0
  - pysocks=1.7.1=py314haa95532_1
  - python=3.14.2=h3bc0a5a_101_cp314
  - python-dateutil=2.9.0post0=py314haa95532_2
  - python-dotenv=1.1.0=py314haa95532_0
  - python-tzdata=2025.3=pyhd3eb1b0_0
  - python_abi=3.14=2_cp314
  - pytz=2025.2=py314haa95532_0
  - pywin32=311=py314h885b0b7_0
  - pyzmq=27.1.0=py314h7149c55_1
  - qt-main=5.15.2=h8b2cd8b_13
  - requests=2.32.5=py314haa95532_1
  - seaborn=0.13.2=py314haa95532_3
  - selenium=4.38.0=py314h114bc41_0
  - setuptools=80.10.1=py314haa95532_0
  - sip=6.12.0=py314h706e071_0
  - six=1.17.0=py314haa95532_0
  - sniffio=1.3.1=py314haa95532_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.51.1=hda9a48d_0
  - stack_data=0.6.3=py314haa95532_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.4=py314h02ab6af_0
  - traitlets=5.14.3=py314haa95532_0
  - trio=0.32.0=py314haa95532_0
  - trio-websocket=0.12.2=py314haa95532_1
  - typing_extensions=4.15.0=py314haa95532_0
  - tzdata=2025c=he532380_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.3=py314haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=py314haa95532_0
  - websocket-client=1.8.0=py314haa95532_0
  - win_inet_pton=1.1.0=py314haa95532_1
  - wsproto=1.3.1=py314haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h6c54ac7_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - ansicolors==1.1.8
      - black==26.1.0
      - bleach==6.3.0
      - click==8.3.1
      - entrypoints==0.4
      - fastjsonschema==2.21.2
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kaggle==1.8.3
      - kagglesdk==0.1.15
      - librt==0.7.8
      - lxml==6.0.2
      - mypy==1.19.1
      - mypy-extensions==1.1.0
      - nbclient==0.10.4
      - nbformat==5.10.4
      - numpy==2.4.2
      - pandas==3.0.0
      - papermill==2.6.0
      - pathspec==1.0.4
      - protobuf==6.33.5
      - python-slugify==8.0.4
      - pytokens==0.4.1
      - pytrends==4.9.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - rpds-py==0.30.0
      - tenacity==9.1.4
      - text-unidecode==1.3
      - tqdm==4.67.2
      - types-requests==2.32.4.20260107
      - types-tqdm==4.67.2.20260202
      - webencodings==0.5.1
prefix: C:\Users\DanishZaheer\anaconda3\envs\data_engg
